// This file is automatically generated by pythoncpp library scripts
// and contains paths to be specified in C++ Python application.
// Please do not modify contents of this file

#include <string>
#include <vector>

namespace Python
{
constexpr char pythonhome[] = "dist/lib/python3.11";
const std::vector<std::string> pythondirs{
	"dist/lib/python3.11",
	"dist/lib/python3.11/lib-dynload",
	"dist/lib/python3.11/site-packages"
};
}